# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: levenshtein.proto

require 'google/protobuf'


descriptor_data = "\n\x11levenshtein.proto\x12\x0blevenshtein\"\x15\n\x05Query\x12\x0c\n\x04text\x18\x01 \x01(\t\"<\n\x04Word\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x17\n\x0fsimilarity_rate\x18\x03 \x01(\x01\"2\n\x0eSearchResponse\x12 \n\x05words\x18\x01 \x03(\x0b\x32\x11.levenshtein.Word2O\n\x12LevenshteinService\x12\x39\n\x06Search\x12\x12.levenshtein.Query\x1a\x1b.levenshtein.SearchResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Levenshtein
  Query = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("levenshtein.Query").msgclass
  Word = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("levenshtein.Word").msgclass
  SearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("levenshtein.SearchResponse").msgclass
end
