# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import profanity_pb2 as profanity__pb2

class ProfanityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectProfanity = channel.unary_unary(
                '/profanity.ProfanityService/DetectProfanity',
                request_serializer=profanity__pb2.TextRequest.SerializeToString,
                response_deserializer=profanity__pb2.ProfanityResponse.FromString,
                )


class ProfanityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectProfanity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfanityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectProfanity': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectProfanity,
                    request_deserializer=profanity__pb2.TextRequest.FromString,
                    response_serializer=profanity__pb2.ProfanityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'profanity.ProfanityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProfanityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectProfanity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profanity.ProfanityService/DetectProfanity',
            profanity__pb2.TextRequest.SerializeToString,
            profanity__pb2.ProfanityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
