# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: profanity.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'profanity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprofanity.proto\x12\tprofanity\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"8\n\x11ProfanityResponse\x12\x12\n\nis_profane\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2[\n\x10ProfanityService\x12G\n\x0f\x44\x65tectProfanity\x12\x16.profanity.TextRequest\x1a\x1c.profanity.ProfanityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profanity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=30
  _globals['_TEXTREQUEST']._serialized_end=57
  _globals['_PROFANITYRESPONSE']._serialized_start=59
  _globals['_PROFANITYRESPONSE']._serialized_end=115
  _globals['_PROFANITYSERVICE']._serialized_start=117
  _globals['_PROFANITYSERVICE']._serialized_end=208
# @@protoc_insertion_point(module_scope)
