# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: levenshtein.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'levenshtein.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11levenshtein.proto\x12\x0blevenshtein\"\x15\n\x05Query\x12\x0c\n\x04text\x18\x01 \x01(\t\"<\n\x04Word\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x17\n\x0fsimilarity_rate\x18\x03 \x01(\x01\"2\n\x0eSearchResponse\x12 \n\x05words\x18\x01 \x03(\x0b\x32\x11.levenshtein.Word2O\n\x12LevenshteinService\x12\x39\n\x06Search\x12\x12.levenshtein.Query\x1a\x1b.levenshtein.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'levenshtein_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERY']._serialized_start=34
  _globals['_QUERY']._serialized_end=55
  _globals['_WORD']._serialized_start=57
  _globals['_WORD']._serialized_end=117
  _globals['_SEARCHRESPONSE']._serialized_start=119
  _globals['_SEARCHRESPONSE']._serialized_end=169
  _globals['_LEVENSHTEINSERVICE']._serialized_start=171
  _globals['_LEVENSHTEINSERVICE']._serialized_end=250
# @@protoc_insertion_point(module_scope)
