# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: levenshtein.proto for package 'levenshtein'
# Original file comments:
# levenshtein.proto

require 'grpc'
require 'levenshtein_pb'

module Levenshtein
  module LevenshteinService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'levenshtein.LevenshteinService'

      rpc :Search, ::Levenshtein::Query, ::Levenshtein::SearchResponse
    end

    Stub = Service.rpc_stub_class
  end
end
