default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: root
  password: df159357
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: db
  database: rails-board

test:
  <<: *default
  database: rails-board-test

production:
  <<: *default
  database: rails-board-prod
