services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: df159357
      POSTGRES_DB: rails-board
    ports:
      - "5432:5432"
    networks:
      - ruby-board

  community-service:
    build:
      context: ./community-service
      dockerfile: Dockerfile
    container_name: community-service
    command: bash -c "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
    networks:
      - ruby-board

  management-service:
    build:
      context: ./management-service
      dockerfile: Dockerfile
    container_name: management-service
    command: bash -c "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
    networks:
      - ruby-board

  bad-word-detector-service:
    build:
      context: ./badword-detector
      dockerfile: Dockerfile
    container_name: bad-word-detector-service
    command: bash -c "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p 3000"
    ports:
      - "50051:50051"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
    networks:
      - ruby-board

  rabbitmq:
    image: "rabbitmq:latest"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ruby-board
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

networks:
  ruby-board:
    driver: bridge
