# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profanity.proto

require 'google/protobuf'


descriptor_data = "\n\x0fprofanity.proto\x12\tprofanity\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"8\n\x11ProfanityResponse\x12\x12\n\nis_profane\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2[\n\x10ProfanityService\x12G\n\x0f\x44\x65tectProfanity\x12\x16.profanity.TextRequest\x1a\x1c.profanity.ProfanityResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Profanity
  TextRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("profanity.TextRequest").msgclass
  ProfanityResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("profanity.ProfanityResponse").msgclass
end
