# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: profanity.proto for package 'profanity'

require 'grpc'
require 'profanity_pb'

module Profanity
  module ProfanityService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'profanity.ProfanityService'

      rpc :DetectProfanity, ::Profanity::TextRequest, ::Profanity::ProfanityResponse
    end

    Stub = Service.rpc_stub_class
  end
end
